version: v1-winbuild-{build}

image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  # - Release # TODO

before_build:
  - cmd: if "%platform%"=="Win32" set msvc=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set msvc=Visual Studio 15 2017 Win64

build_script:
  - powershell ".\ci\do-ut.ps1;exit $LASTEXITCODE"
